---
title: "Régressions multiniveau Nature"
output: html_document
---

```{r setup, include=FALSE}
source("recodages.R", encoding = "UTF-8")
knitr::opts_chunk$set(echo = TRUE)

library(glmmTMB)
library(tidyverse)
library(gtsummary)


climatRegr_r <- mutate(climatRegr_r,
                       sexenum=if_else(sexe == "Femme", 1, 0),
                       sexenum_jeunes=if_else(agenum < 40, sexenum, NA_real_),
                       sexenum_vieux=if_else(agenum >= 40, sexenum, NA_real_),
                       
                       sexenum_inf35ans=if_else(agenum < 32, sexenum, NA_real_),
                       sexenum_35_55ans=if_else(agenum > 31 & agenum < 45, sexenum, NA_real_),
                       sexenum_plus55ans=if_else(agenum > 55, sexenum, NA_real_),
                       
                       sexenum_rangA=if_else(sitpro2 == "Directeur·rice de recherche" | sitpro2 == "Professeur·e des universités", sexenum, NA_real_),
                       sexenum_autre=if_else(sitpro2 != "Directeur·rice de recherche" & sitpro2 != "Professeur·e des universités", sexenum, NA_real_),

                       carrierenum=if_else(carriere == "Oui", 1, 0),
                       carriere_titnum=if_else(carriere_tit == "Oui", 1, 0),
                       carriere_precnum=if_else(carriere_prec == "Oui", 1, 0),
                       rangAnum=if_else(sitpro2 == "Directeur·rice de recherche" | sitpro2 == "Professeur·e des universités", 1, 0),
                       rangBnum=if_else(sitpro2 == "Chargé·e de recherche" | sitpro2 == "Maître·sse de conférences" | sitpro2 == "Ingénieur·e de recherche", 1, 0),
                       titnum=if_else(sitpro2 == "Directeur·rice de recherche" | sitpro2 == "Professeur·e des universités" | sitpro2 == "Chargé·e de recherche" | sitpro2 == "Maître·sse de conférences" | sitpro2 == "Ingénieur·e de recherche", 1, 0),
                       precairenum=if_else(sitpro2 == "Post-doctorant·e" | sitpro2 == "ATER", 1, 0),
                       nbpublis2=pmin(nbpublis, 100),
                       nbpublis2_log=log(nbpublis2+1),
                       nbpublis2_log_divcoaut=log((nbpublis2+1)/coauteur),
                       nbpublis2_log_divcoauthal=log((nbpublis2+1)/coauteur_hal),
                       nbpublisang_log=log(nbpublisang+1),
                       nopubli=ifelse(nbpublis == 0, 1, 0),
                       tourisme=startsWith(as.character(apportconf.tourisme), "Oui"),
                       revenuTete_log=log(revenuTete),
                       revenuAdulte_log=log(revenuAdulte),
                       revenuMenage_log=log(revenuMenage),
                       revenuTete=revenuTete/1000,
                       revenuAdulte=revenuAdulte/1000,
                       revenuMenage=revenuMenage/1000,
                       parbacp5=dippar.p == "Bac +4 ou 5" | dippar.p == "Doctorat" |
                           dippar.m == "Bac +4 ou 5" | dippar.m == "Doctorat",
                       un_parent_publicnum = ifelse(un_parent_public=="Oui", 1,0),
                       enfant_moins_6_ansnum = ifelse(enfantsage_rec=="Moins de 6 ans", 1, 0),
                       avionpersonum=recode(avionperso,
                                            "Aucun aller-retour"=0,
                                            "1 ou 2 allers-retours"=1.5,
                                            "3 ou 4 allers-retours"=2.5,
                                            "Plus de 5 allers-retours"=6),
                       materielnum=recode(maxmateriel,
                                          "Aucun materiel" = 0,
                                          "Très grande infrastructure" = 2, 
                                          "Dispositifs extensifs" = 2,
                                          "Petit materiel" = 1,
                                          "Materiel couteux" = 3,
                                          "Materiel très couteux" = 5,
                                          "Materiel couteux et très couteux" = 7,
                                          .default = 0,
                                          .missing = 0),
                       # coutmateriel_old=recode(maxmateriel, 
                       #                     "Petit materiel" = 1,
                       #                     "Materiel couteux" = 3,
                       #                     "Materiel très couteux" = 6,
                       #                     "Materiel couteux et très couteux" = 7,
                       #                     .default = 0,
                       #                     .missing = 0),
                       coutmateriel=case_when(materiel.trescouteux == "Oui" & materiel.couteux  == "Oui" ~ 7,
                                              materiel.trescouteux == "Oui" ~ 6,
                                              materiel.couteux == "Oui" ~ 3,
                                              materiel.petit == "Oui" ~ 1,
                                              !is.na(materiel) ~ 0),
                       materiel.experimentalnum=case_when(materiel.trescouteux == "Oui" ~ 1,
                                                          materiel.couteux  == "Oui" ~ 1,
                                                          materiel.petit == "Oui" ~ 1,
                                                          !is.na(materiel) ~ 0),
                       # coutmateriel=case_when(materiel.tgir == "Oui" ~ 4,
                       #                        materiel.trescouteux == "Oui" | materiel.extensif == "Oui" ~ 3,
                       #                        materiel.couteux == "Oui" ~ 2,
                       #                        materiel.petit == "Oui" ~ 1,
                       #                        !is.na(materiel) ~ 0),
                       materiel.extensifnum=ifelse(materiel.extensif == "Oui", 1, 0),
                       materiel.tgirnum=ifelse(materiel.tgir == "Oui", 1, 0),
                       materiel.infonum=ifelse(materiel.info == "Oui", 1, 0),
                       materiel.tgirinfonum=ifelse(materiel.tgir == "Oui" | materiel.info == "Oui", 1, 0),
                       chgtpratiquenum=as.numeric(fct_relevel(chgtpratique, "Non, pas du tout d'accord",
                                                              "Non, plutôt pas d'accord", "Sans opinion",
                                                              "Oui, plutôt d'accord",
                                                              "Oui, tout à fait d'accord")) - 1,
                       preoccupe2num=as.numeric(fct_relevel(preoccupe2, "Pas du tout préoccupé·e", "Sans opinion",
                                                            "Un peu préoccupé·e", "Assez préoccupé·e", 
                                                            "Très préoccupé·e", "Extrêmement préoccupé·e")) - 1,
                       paienum=as.numeric(fct_relevel(paie, c("Très bien payé·e", "Bien payé·e", "Correctement payé·e", "Mal payé·e", "Très mal payé·e"))),
                       solreducrechnum=as.numeric(fct_rev(solreducrech)) - 1,
                       projet=Profin_Mb_Resp == "Membre d'au moins 1 projet financé" | Profin_Mb_Resp == "Responsable d'au moins 1 projet financé",
                       projet_fr=particip_ANR | particip_Fr,
                       projet_intern=particip_Europ | particip_Intern,
                       mb_aumoins1projet=if_else(projets.anr_m2 == "Membre projet ANR oui" |
                                                     projets.france_m2 == "Membre projet France oui" |
                                                     projets.europe_m2 == "Membre projet européen oui" |
                                                     projets.inter_m2 == "Membre projet international oui" |
                                                     projets.prive_m2 == "Membre projet privé oui",
                                                 1, 0),
                       resp_aumoins1projet=if_else(projets.anr_r2 == "Responsable projet ANR oui" |
                                                       projets.france_r2 == "Responsable projet France oui" |
                                                       projets.europe_r2 == "Responsable projet européen oui" |
                                                       projets.inter_r2 == "Responsable projet international oui" |
                                                       projets.prive_r2 == "Responsable projet privé oui",
                                                   1, 0),
                       mbresp_aumoins1projet=if_else(mb_aumoins1projet == 1 | resp_aumoins1projet == 1,
                                                     1, 0),
                       idfnum=ifelse(trav_zone == "IDF", 1, 0),
                       loinnum=ifelse(trav_zone == "loin", 1, 0),
                       res.aeroport.bisquare=res.aeroport.bisquare120,
                       trav.aeroport.bisquare=trav.aeroport.bisquare120,
                       across(starts_with("solrisqreducavion") | starts_with("solrisqreducmateriel"),
                               ~ na_if(., "Non concerné·e") == "C'est probable mais ce n'est pas un problème",
                                  # na_if(., "Non concerné·e") == "C'est probable et c'est un problème",
                              .names="{.col}num"),
                       across(starts_with("solreducperso"),
                               ~ na_if(., "Non concerné·e") == "Oui, mais de moins d'un tiers" |
                                  na_if(., "Non concerné·e") == "Oui, d’au moins un tiers",
                              .names="{.col}num"))

climatRegr_r$solrisqreducavion <- rowSums(select(climatRegr_r, starts_with("solrisqreducavion") & ends_with("num")),
                                          na.rm=TRUE)
climatRegr_r$solrisqreducavion <- if_else(rowSums(!is.na(select(climatRegr_r, solrisqreducavion.donneesnum,
                                                               solrisqreducavion.diffusionnum,
                                                               solrisqreducavion.bureaucratienum))) == 0,
                                          NA_real_,
                                          rowSums(select(climatRegr_r, solrisqreducavion.donneesnum,
                                                         solrisqreducavion.diffusionnum,
                                                         solrisqreducavion.bureaucratienum),
                                                  na.rm=TRUE))
# climatRegr_r$solrisqreducavion <- if_else(rowSums(!is.na(select(climatRegr_r, solrisqreducavion.isolernum,
#                                                                solrisqreducavion.avantagesnum,
#                                                                solrisqreducavion.insertionnum))) == 0,
#                                           NA_real_,
#                                           rowSums(select(climatRegr_r, solrisqreducavion.isolernum,
#                                                                solrisqreducavion.avantagesnum,
#                                                                solrisqreducavion.insertionnum),
#                                                   na.rm=TRUE))

# climatRegr <- group_by(climatRegr, unite.labintel) %>%
#     filter(n() > 1)
# 
# climatRegr <- group_by(climatRegr, discipline) %>%
#     filter(n() > 1)


# ACP score écolo

climatRegr_r <- mutate(climatRegr_r,
                       opinionecolo.decroissance_num=as.numeric(
                           fct_relevel(
                               opinionecolo.decroissance, 
                               "Pas du tout d'accord", 
                               "Plutôt pas d'accord", 
                               "Sans opinion", 
                               "Plutôt d'accord",
                               "Tout à fait d'accord")) - 1,
                       opinionecolo.cata_num=as.numeric(
                           fct_relevel(
                               opinionecolo.cata, 
                               "Pas du tout d'accord", 
                               "Plutôt pas d'accord", 
                               "Sans opinion", 
                               "Plutôt d'accord",
                               "Tout à fait d'accord")) - 1,
                       opinionecolo.techno_num=as.numeric(
                           fct_relevel(
                               opinionecolo.techno, 
                               "Pas du tout d'accord", 
                               "Plutôt pas d'accord", 
                               "Sans opinion", 
                               "Plutôt d'accord",
                               "Tout à fait d'accord")) - 1,
                       opinionecolo.proteger_num=as.numeric(
                           fct_relevel(
                               opinionecolo.proteger, 
                               "Pas du tout d'accord", 
                               "Plutôt pas d'accord", 
                               "Sans opinion", 
                               "Plutôt d'accord",
                               "Tout à fait d'accord")) - 1,
                       opinionecolo.efforts_num=as.numeric(
                           fct_relevel(
                               opinionecolo.efforts, 
                               "Pas du tout d'accord", 
                               "Plutôt pas d'accord", 
                               "Sans opinion", 
                               "Plutôt d'accord",
                               "Tout à fait d'accord")) - 1,
                       opinionecolo.contraintes_num=as.numeric(
                           fct_relevel(
                               opinionecolo.contraintes, 
                               "Pas du tout d'accord", 
                               "Plutôt pas d'accord", 
                               "Sans opinion", 
                               "Plutôt d'accord",
                               "Tout à fait d'accord")) - 1,
                       opinionecolo.effondrement_num=as.numeric(
                           fct_relevel(
                               opinionecolo.effondrement, 
                               "Pas du tout d'accord", 
                               "Plutôt pas d'accord", 
                               "Sans opinion", 
                               "Plutôt d'accord",
                               "Tout à fait d'accord")) - 1)

climatRegr_r$dixannees.marche_num <- climatRegr_r$dixannees.marche %>%
    fct_recode(
        "1" = "Oui",
        "0" = "Non",
        NULL = "Je ne souhaite pas répondre"
    ) %>%
    as.character() %>%
    as.numeric()

climatRegr_r$dixannees.asso_num <- climatRegr_r$dixannees.asso %>%
    fct_recode(
        "1" = "Oui",
        "0" = "Non",
        NULL = "Je ne souhaite pas répondre"
    ) %>%
    as.character() %>%
    as.numeric()
climatRegr_r$dixannees.giec_num <- climatRegr_r$dixannees.giec %>%
    fct_recode(
        "1" = "Oui",
        "0" = "Non",
        NULL = "Je ne souhaite pas répondre"
    ) %>%
    as.character() %>%
    as.numeric()
climatRegr_r$dixannees.vote_num <- climatRegr_r$dixannees.vote %>%
    fct_recode(
        "1" = "Oui",
        "0" = "Non",
        NULL = "Je ne souhaite pas répondre"
    ) %>%
    as.character() %>%
    as.numeric()
climatRegr_r$dixannees.bilan_num <- climatRegr_r$dixannees.bilan %>%
    fct_recode(
        "1" = "Oui",
        "0" = "Non",
        NULL = "Je ne souhaite pas répondre"
    ) %>%
    as.character() %>%
    as.numeric()

base_acp <- climatRegr_r[,
                         c("opinionecolo.decroissance_num",
                           "opinionecolo.cata_num",
                           "opinionecolo.techno_num",
                           "opinionecolo.proteger_num",
                           "opinionecolo.efforts_num",
                           "opinionecolo.contraintes_num",
                           "opinionecolo.effondrement_num",
                           "preoccupe2num",
                           "dixannees.marche_num", 
                           "dixannees.giec_num", 
                           "dixannees.vote_num", 
                           "dixannees.asso_num", 
                           "dixannees.bilan_num"
                         )]

# Ne pas imputer les personnes qui ont répondu à moins de la moitié des questions
manquant_acp <- rowSums(is.na(base_acp)) > 6
base_acp_complete <- missMDA::imputePCA(base_acp[!manquant_acp,], 1)$completeObs
acp <- FactoMineR::PCA(base_acp_complete)
climatRegr_r$ScoreEcoloACP <- NA
climatRegr_r$ScoreEcoloACP[!manquant_acp] <- acp$ind$coord[,1]

# Liste des variables à centrer par labo/discipline
vars_centrer <- c( "agenum", "nbpublis2", "nbpublis2_log", "coauteur", "coauteur_hal",
                  "nbpublis2_log_divcoaut", "nbpublis2_log_divcoauthal",
                  "ScoreEcolo", "ScoreEcoloACP",
                  "ScoreInternational", "ScoreInternational_perso",
                  "ScoreInternational_pro", "ScoreInternational_pro2",
                  "ScoreInternational_pro3", "ScoreInternational_pro4",
                  "tourisme", "avionpersonum", "chgtpratiquenum", "preoccupe2num", "solreducrechnum",
                  "projet", "projet_fr", "projet_intern",
                  "revenuTete", "revenuAdulte", "revenuMenage",
                  "revenuTete_log", "revenuAdulte_log", "revenuMenage_log",
                  "paienum", "parbacp5",
                  "materielnum", "coutmateriel", "enfants_foyer",
                  "res.aeroport.bisquare", "trav.aeroport.bisquare",
                  "solrisqreducavion",
                  names(select(climatRegr_r, starts_with("solrisqreducavion") & ends_with("num"))),
                  names(select(climatRegr_r, starts_with("solreducperso") & ends_with("num"))))

# Liste des variables à moyenner par labo/discipline
vars <- c(vars_centrer, "sexenum", "sexenum_jeunes", "sexenum_vieux", "sexenum_rangA", "sexenum_autre",
          "carrierenum", "carriere_titnum", "carriere_precnum", "couple1",
          "rangAnum", "rangBnum", "titnum", "precairenum",
          "mb_aumoins1projet", "resp_aumoins1projet", "mbresp_aumoins1projet",
          "idfnum", "loinnum",  "un_parent_publicnum", "enfant_moins_6_ansnum",
          "nopubli", "materiel.extensifnum", "materiel.tgirnum", "materiel.infonum",
          "materiel.tgirinfonum", "materiel.experimentalnum")

# Standardiser les variables individuelles pour que leur écart-type soit égal à 1
climatRegr_r[vars_centrer] <- scale(climatRegr_r[vars_centrer])

# Création des moyennes par discipline (_discipline) et des variables centrées par discipline (_cdisc)
climatRegr_r <- group_by(climatRegr_r, discipline_detaillee) %>%
    mutate(across(all_of(vars), ~ mean(.x, na.rm=TRUE), .names="{.col}_disc"),
           across(all_of(vars), ~ .x - mean(.x, na.rm=TRUE), .names="{.col}_cdisc")) %>%
    ungroup()

# Création des moyennes par labo (_labo),
# des moyennes par labo centrées par discipline(s) (_labodisc),
# et des variables centrées par labo (_clabo)
climatRegr_r <- group_by(climatRegr_r, unite.labintel) %>%
    mutate(across(all_of(vars), ~ mean(.x, na.rm=TRUE), .names="{.col}_labo"),
           across(all_of(vars), ~ mean(.x, na.rm=TRUE) - mean(get(paste0(cur_column(), "_disc")), na.rm=TRUE), .names="{.col}_labodisc"),
           across(all_of(vars), ~ .x - mean(.x, na.rm=TRUE), .names="{.col}_clabo")) %>%
    ungroup()

# Création des variables centrées par labo et discipline (_c)
# On rajoute la moyenne de la variable d'origine
# pour que leur moyenne soit à 0 alors qu'on a soustrait deux fois la moyenne
climatRegr_r[paste0(vars, "_c")] <-
    select(climatRegr_r, all_of(vars)) -
    select(climatRegr_r, all_of(paste0(vars, "_labo"))) -
    select(climatRegr_r, all_of(paste0(vars, "_disc"))) +
    transmute(climatRegr_r, across(all_of(vars), ~ mean(.x, na.rm=TRUE)))

# Création des variables centrées par labo centrés par discipline(s) (_clabodisc)
climatRegr_r[paste0(vars, "_clabodisc")] <-
    select(climatRegr_r, all_of(vars)) -
    select(climatRegr_r, all_of(paste0(vars, "_labodisc"))) -
    select(climatRegr_r, all_of(paste0(vars, "_disc"))) +
    transmute(climatRegr_r, across(all_of(vars), ~ mean(.x, na.rm=TRUE)))

# Standardiser les variables au niveau labo et discipline
# pour que l'écart-type des moyennes par labo/discipline soit égal à 1
sd_labo <- select(climatRegr_r, unite.labintel, all_of(paste0(vars, "_labo"))) %>%
    group_by(unite.labintel)  %>%
    summarize(across(everything(), ~ mean(.x, na.rm=TRUE))) %>%
    select(-unite.labintel) %>%
    apply(2, sd, na.rm=T)
climatRegr_r[names(sd_labo)] <- sweep(climatRegr_r[names(sd_labo)], 2, sd_labo, "/")

sd_labodisc <- select(climatRegr_r, unite.labintel, all_of(paste0(vars, "_labodisc"))) %>%
    group_by(unite.labintel)  %>%
    summarize(across(everything(), ~ mean(.x, na.rm=TRUE))) %>%
    select(-unite.labintel) %>%
    apply(2, sd, na.rm=T)
climatRegr_r[names(sd_labodisc)] <- sweep(climatRegr_r[names(sd_labodisc)], 2, sd_labodisc, "/")

sd_disc <- select(climatRegr_r, discipline_detaillee, all_of(paste0(vars, "_disc"))) %>%
    group_by(discipline_detaillee)  %>%
    summarize(across(everything(), ~ mean(.x, na.rm=TRUE))) %>%
    select(-discipline_detaillee) %>%
    apply(2, sd, na.rm=T)
climatRegr_r[names(sd_disc)] <- sweep(climatRegr_r[names(sd_disc)], 2, sd_disc, "/")

# Standardiser les variables individuelles centrées pour que leur écart-type soit égal à 1
climatRegr_r[c(paste0(vars, "_c"), paste0(vars, "_clabo"), paste0(vars, "_clabodisc"), paste0(vars, "_cdisc"))] <-
    scale(climatRegr_r[c(paste0(vars, "_c"), paste0(vars, "_clabo"), paste0(vars, "_clabodisc"), paste0(vars, "_cdisc"))])
```



```{r}
reg0 <- glmmTMB(round(volsdist_tot_imp) ~ sexenum + sexenum_labo + sexenum_disc +
                    ageAgr + agenum_labo + agenum_disc +
                    sitpro2 +
                    nbpublis2_log_divcoauthal + nbpublis2_log_divcoauthal_labo + nbpublis2_log_divcoauthal_disc +
                    ScoreInternational_pro4 + ScoreInternational_pro4_labo + ScoreInternational_pro4_disc +
                    mbresp_aumoins1projet + mbresp_aumoins1projet_labo + mbresp_aumoins1projet_disc +
                    materiel.infonum + materiel.infonum_labo + materiel.infonum_disc +
                    # materiel.tgirnum + materiel.tgirnum_labo + materiel.tgirnum_disc +
                    # materiel.tgirinfonum + materiel.tgirinfonum_labo + materiel.tgirinfonum_disc +
                    materiel.experimentalnum + materiel.experimentalnum_labo + materiel.experimentalnum_disc +
                    (1 | unite.labintel) + (1 | discipline_detaillee),
                family="tweedie",
                data=climatRegr_r,
                control=glmmTMBControl(parallel=4))

reg1 <- update(reg0, ~ . +
                   # idfnum + idfnum_labo + idfnum_disc +
                   #loinnum + #loinnum_labo + loinnum_disc +
                   #trav_zone +
                   # res.aeroport.bisquare + res.aeroport.bisquare_labo + res.aeroport.bisquare_disc +
                   #I(res.dep %in% c(75, 77, 92:95)) +
                   # trav.aeroport.bisquare + trav.aeroport.bisquare_labo + trav.aeroport.bisquare_disc +
                   #ScoreInternational_perso + ScoreInternational_perso_labo + ScoreInternational_perso_disc +
                   # paienum + paienum_labo + paienum_disc +
                   carrierenum + carrierenum_labo + carrierenum_disc +
                   ScoreEcoloACP + ScoreEcoloACP_labo + ScoreEcoloACP_disc +
                   avionpersonum + avionpersonum_labo + avionpersonum_disc +
                   revenuAdulte_log + revenuAdulte_log_labo + revenuAdulte_log_disc)


reg2 <- update(reg1, ~ . +
                   enfantsage_rec*sexenum - sexenum_disc + sexenum_jeunes_disc + sexenum_vieux_disc +
                   ScoreEcoloACP*ScoreInternational_pro4 + ScoreEcoloACP*ScoreInternational_pro4_labo + ScoreEcoloACP*ScoreInternational_pro4_disc)

tbls <- lapply(list(reg0, reg1, reg2),
               function(m) tbl_regression(m, exponentiate=TRUE, add_estimate_to_reference_rows=TRUE, tidy_fun=broom.mixed::tidy) %>% add_glance_table())
tbl_merge(tbls, paste0("M", 0:(length(tbls)-1))) %>%
      modify_table_body(~ .x %>% arrange(row_type == "glance_statistic", endsWith(variable, "sd__(Intercept)")))
```

```{R}
library(marginaleffects)
mydf <- avg_predictions(reg2, newdata=reg2$frame, re.form=NA,
                        variables = list("ScoreEcoloACP"=quantile(climatRegr_r$ScoreEcoloACP, na.rm=T, c(.1, .9)),
                                         "ScoreInternational_pro4_disc"=quantile(climatRegr_r$ScoreInternational_pro4_disc, na.rm=T, c(.1, .5, .9))))
mydf %>% as_tibble() %>%
    mutate(score=factor(ScoreInternational_pro4_disc, levels=sort(unique(ScoreInternational_pro4_disc)),
                        labels=c("1er décile", "Médiane", "9e décile")) %>%
               fct_rev()) %>%
    ggplot(aes(x = ScoreEcoloACP, y = estimate, colour = score, shape = score,
               ymin=conf.low, ymax=conf.high)) +
    geom_line() +
    # geom_pointrange() +
    geom_errorbar(width=0.15, show.legend=FALSE) +
    geom_point(size=2) +
    coord_cartesian(ylim=c(0, NA)) +
    labs(x="Score écologique individuel", y="Distance parcourue en avion en 2019 (en km)",
         color="Score international de la discipline",
         shape="Score international de la discipline") +
    scale_color_manual(values=c( "#ca0020", "black", "#0571b0")) +
    scale_y_continuous(breaks=c(0, 2500, 5000, 7500, 10000, 12500), minor_breaks=NULL) +
    scale_x_continuous(minor_breaks=NULL) +
    theme_light()

# Version qui met les autres variables à leur moyenne
# vcov=TRUE pour avoir les intervalles de confiance
# plot_predictions(reg2, newdata=reg2$frame, re.form=NA,
#                         condition = list("ScoreEcoloACP"=c(-2, 2), "ScoreInternational_pro4_disc"=c(-1, 0, 1)))
```

# Effet des enfants selon le sexe

```{R}
# library(ggeffects)
# mydf <- ggpredict(reg1, terms = list(sexenum=c(0, 1), enfantsage_rec=levels(climatRegr_r$enfantsage_rec)))
# mydf <- ggemmeans(reg1, terms = c("sexenum", "enfantsage_rec"))
# 
# mydf %>% as_tibble() %>%
#     mutate(sexe=fct_recode(as.character(x), "Femmes"="1", "Hommes"="0")) %>%
#     ggplot(aes(x = sexe, y = predicted, colour = group, ymin=conf.low, ymax=conf.high)) +
#     geom_pointrange(position=position_dodge(width=0.5)) +
#     coord_cartesian(ylim=c(0, NA)) +
#     labs(x="", y="Distance parcourue en avion en 2019 (en km)",
#          color="Enfants à charge :")

# Nouvelle version avec le nouveau paquet, donne la même chose que ggeffect et ggemmeans
# Mais les valeurs sont bien trop basses par rapport à ce que prédit predict.glmmTMB
# mydf <- modelbased::estimate_means(reg1, by=c("sexenum", "enfantsage_rec"), estimate="average", backend="emmeans")
# mydf %>% as_tibble() %>%
#     mutate(sexe=fct_recode(as.character(sexenum), "Femmes"="1", "Hommes"="0")) %>%
#     ggplot(aes(x = sexe, y = Mean, colour = enfantsage_rec, ymin=CI_low, ymax=CI_high)) +
#     geom_pointrange(position=position_dodge(width=0.5)) +
#     coord_cartesian(ylim=c(0, NA)) +
#     labs(x="", y="Distance parcourue en avion en 2019 (en km)",
#          color="Enfants à charge :")

# Autre version utilisant directement marginaleffects
library(marginaleffects)
mydf <- avg_predictions(reg1, re.form=NA, variables=c("sexenum", "enfantsage_rec"))
mydf %>% as_tibble() %>%
    mutate(sexe=fct_recode(as.character(sexenum), "Femmes"="1", "Hommes"="0")) %>%
    ggplot(aes(x = sexe, y = estimate, colour = enfantsage_rec, shape=enfantsage_rec,
               ymin=conf.low, ymax=conf.high)) +
    geom_errorbar(width=0.1, position=position_dodge(width=0.5)) +
    geom_point(position=position_dodge(width=0.5)) +
    coord_cartesian(ylim=c(0, NA)) +
    labs(x="", y="Distance parcourue en avion en 2019 (en km)",
         color="Enfants à charge",
         shape="Enfants à charge") +
    scale_color_brewer(palette="Set1") +
    theme_light()
```
# Graphique des coefficients

```{R}

library(broom.mixed)
library(wesanderson)
a <- tidy(reg1, conf.int = T, exponentiate=T)
a <- a[a$term %in% c("agenum", "agenum_labo", "agenum_disc",
                     "sexenum" , "sexenum_labo" , "sexenum_disc" , 
                     "ScoreEcoloACP" , "ScoreEcoloACP_labo" , 
                     "ScoreEcoloACP_disc" ,
                     "revenuTete" , "revenuTete_labo" , "revenuTete_disc",
                     "revenuAdulte" , "revenuAdulte_labo" , "revenuAdulte_disc",
                     "carriere_titnum" ,"carriere_titnum_disc" ,"carriere_titnum_labo" ,
                     "nbpublis2" , "nbpublis2_labo" , "nbpublis2_disc" ,
                     "ScoreInternational_pro" , "ScoreInternational_pro_labo" , 
                     "ScoreInternational_pro_disc" ,
                     "avionpersonum", "avionpersonum_labo", "avionpersonum_disc",
                     "respprojetnum", "respprojetnum_labo", "respprojetnum_disc"),]

## Recodage de a$term en a$term_rec
a$term_rec <- a$term %>%
    fct_recode(
        "Vols privés" = "avionpersonum",
        "Vols privés" = "avionpersonum_disc",
        "Vols privés" = "avionpersonum_labo",
        "Moment-clé de la carrière" = "carriere_titnum",
        "Moment-clé de la carrière" = "carriere_titnum_disc",
        "Moment-clé de la carrière" = "carriere_titnum_labo",
        "Nombre de publications" = "nbpublis2",
        "Nombre de publications" = "nbpublis2_disc",
        "Nombre de publications" = "nbpublis2_labo",
        "Niveau de vie" = "revenuTete",
        "Niveau de vie" = "revenuTete_disc",
        "Niveau de vie" = "revenuTete_labo",
        "Revenu par adulte" = "revenuAdulte",
        "Revenu par adulte" = "revenuAdulte_disc",
        "Revenu par adulte" = "revenuAdulte_labo",
        "Sensibilité à l'écologie" = "ScoreEcoloACP",
        "Sensibilité à l'écologie" = "ScoreEcoloACP_disc",
        "Sensibilité à l'écologie" = "ScoreEcoloACP_labo",
        "Internationalisation" = "ScoreInternational_pro",
        "Internationalisation" = "ScoreInternational_pro_disc",
        "Internationalisation" = "ScoreInternational_pro_labo",
        "Sexe" = "sexenum",
        "Sexe" = "sexenum_disc",
        "Sexe" = "sexenum_labo",
        "Âge" = "agenum",
        "Âge" = "agenum_disc",
        "Âge" = "agenum_labo",
        "Responsable de projet" = "respprojetnum",
        "Responsable de projet" = "respprojetnum_disc",
        "Responsable de projet" = "respprojetnum_labo"
    )
a$group <- case_when(grepl("_labo", a$term) ~ "Laboratoire",
                     grepl("_disc", a$term) ~ "Discipline",
                     TRUE ~ "Individu")
a <- as.data.frame(a)

## Réordonnancement de a$term_rec
a$term_rec <- a$term_rec %>%
    fct_relevel(
        "Revenu par adulte", "Vols privés", "Sensibilité à l'écologie",
        "Responsable de projet", "Internationalisation",
        "Nombre de publications", "Moment-clé de la carrière", "Sexe", "Âge"
    )


## Réordonnancement de a$group
a$group <- a$group %>%
    fct_relevel( "Discipline", "Laboratoire",
                 "Individu"
    )
a$shape <- ifelse(a$p.value<=0.05, "", "non")
ggplot(a, aes(x=estimate, y=term_rec, group=group, color=group, shape=group)) +
    geom_pointrange(
        aes(xmin =  conf.low, xmax = conf.high, 
            color = group,
            shape=paste(group, shape)),
        position = position_dodge(0.4)
    )+geom_vline(xintercept =1)+
    guides(color = guide_legend(reverse = TRUE),shape=F)+
    theme_minimal()+
    scale_color_manual(values=wes_palette(n=3, name="GrandBudapest1"))+
    labs(x="", y="", color="Niveau")+
    scale_shape_manual(values=c(0, 15, 1, 16,2,17 ))
```


# Figure 5 : Distance parcourue en avion selon la proportion de femmes dans chaque discipline agrégée

```{r}
library(ggrepel)
climatRegr_r %>%
    group_by(discipline_agr5) %>%
    summarize(sexe=mean(sexenum, na.rm=TRUE),
              dist=mean(volsdist_tot_imp, na.rm=TRUE),
              n=n()) %>%
    drop_na() %>%
    ggplot(aes(x=sexe, y=dist, weight=n))+
    geom_smooth(method=lm)+theme_minimal()+
    geom_point(aes(size=n))+
    geom_text_repel(aes(label=discipline_agr5), max.overlaps = Inf)+
    scale_x_continuous(labels=scales::percent) +
    guides(size="none") +
    labs(x = "Proportion de femmes (en %)", y = "Distance parcoure en avion en 2019 (en km)")
weights::wtd.cor(a, d, weight=d)


```

# Différents motifs de vol

```{r}
regdist0 <- update(reg0, volsdist_tot ~ .)
regdistconf0 <- update(reg0, volsdist_totconf ~ .)
regdistsejrech0 <- update(reg0, volsdist_totsejrech ~ .)
regdistworkshop0 <- update(reg0, volsdist_totworkshop ~ .)
regdistcours0 <- update(reg0, volsdist_totcours ~ .)
regdistterrain0 <- update(reg0, volsdist_totterrain ~ .)
# regdisteval0 <- update(reg0, volsdist_toteval ~ .)
#regdistjury0 <- update(reg0, volsdist_totjury ~ .)
# regdistautre0 <- update(reg0, volsdist_totautre ~ .)

tbls <- lapply(lst(reg0, reg1, reg2, regdist0, regdistconf0, regdistterrain0, regdistsejrech0, regdistworkshop0
                   # , regdistcours0, regdisteval0, regdistautre0
                   ),
               function(m) tbl_regression(m, exponentiate=TRUE, add_estimate_to_reference_rows=TRUE, conf.int=FALSE))
tbl_merge(tbls, names(tbls))

```

